fib : fibonacci.cpp func.cpp minfunc.hpp
	g++ -Wall -o fib fibonacci.cpp func.cpp
gsec : golden_section.cpp func.cpp minfunc.hpp
	g++ -Wall -o gsec golden_section.cpp func.cpp
swann : swann.cpp func.cpp minfunc.hpp
	g++ -Wall -o swann swann.cpp func.cpp
nraph : newton_raphson.cpp gfunc.cpp minfunc.hpp
	g++ -Wall -o nraph newton_raphson.cpp gfunc.cpp
all : fib gsec swann nraph
